export const INSTITUTIONS = {
    AMUST: "Ahsania Mission University of Science and Technology",
    AUST: "Ahsanullah University of Science and Technology",
    AIUB: "American International University-Bangladesh",
    AKMU: "Anwer Khan Modern University",
    ASA: "ASA University Bangladesh",
    AUW: "Asian University for Women",
    AUB: "Asian University of Bangladesh",
    ADUST: "Atish Dipankar University of Science and Technology",
    BU: "Bandarban University",
    BSMMU: "Bangabandhu Sheikh Mujib Medical University",
    BSMRAU: "Bangabandhu Sheikh Mujibur Rahman Agricultural University",
    BSMRAAU: "Bangabandhu Sheikh Mujibur Rahman Aviation And Aerospace University",
    BSMRDU: "Bangabandhu Sheikh Mujibur Rahman Digital University",
    BSMRMU: "Bangabandhu Sheikh Mujibur Rahman Maritime University",
    BSMRSTU: "Bangabandhu Sheikh Mujibur Rahman Science and Technology University",
    BSMRU: "Bangabandhu Sheikh Mujibur Rahman University",
    BSFMU: "Bangamata Sheikh Fazilatunnesa Mujib Medical University",
    BSFSTU: "Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University",
    BAU: "Bangladesh Agricultural University",
    BIU: "Bangladesh Islami University",
    BnU: "Bangladesh University",
    BUBT: "Bangladesh University of Business and Technology",
    BUET: "Bangladesh University of Engineering and Technology",
    BUHS: "Bangladesh University of Health Sciences",
    BUP: "Bangladesh University of Professionals",
    BUTex: "Bangladesh University of Textiles",
    GUT: "Begum Gulchemonara Trust University",
    BRUR: "Begum Rokeya University, Rangpur",
    BGMEA: "BGMEA University of Fashion and Technology",
    BRACU: "BRAC University",
    BrU: "Britannia University",
    CUB: "Canadian University of Bangladesh",
    CCNUST: "CCN University of Science and Technology",
    CUST: "Central University of Science and Technology",
    CWU: "Central Women's University",
    CSTU: "Chandpur Science and Technology University",
    CBGMEAU: "Chattogram BGMEA University of Fashion and Technology",
    CIU: "Chittagong Independent University",
    CMU: "Chittagong Medical University",
    CUET: "Chittagong University of Engineering and Technology",
    CVA: "Chittagong Veterinary and Animal Sciences University",
    CU: "City University",
    CU2: "Comilla University",
    CBIU: "Cox's Bazar International University",
    DIU: "Daffodil International University",
    DIU2: "Dhaka International University",
    DUET: "Dhaka University of Engineering and Technology",
    EDU: "East Delta University",
    EWU: "East West University",
    EaUB: "Eastern University, Bangladesh",
    EUB: "European University of Bangladesh",
    Exim: "Exim Bank Agricultural University of Bangladesh",
    FIU: "Fareast International University",
    FU: "Feni University",
    FCUB: "First Capital University of Bangladesh",
    GUB: "German University Bangladesh",
    GlUB: "Global University Bangladesh",
    GBU: "Gono Bishwabidyalay",
    GrUB: "Green University of Bangladesh",
    HSTU: "Hajee Mohammad Danesh Science and Technology University",
    HUB: "Hamdard University of Bangladesh",
    HAU: "Hobiganj Agricultural University",
    IBAIS: "IBAIS University",
    IUB: "Independent University, Bangladesh",
    IIUST: "International Islami University of Science and Technology",
    IIUC: "International Islamic University, Chittagong",
    ISU: "International Standard University",
    IUBAT: "International University of Business Agriculture and Technology",
    IIU: "Ishakha International University, Bangladesh",
    IAU: "Islamic Arabic University",
    IU: "Islamic University",
    IUT: "Islamic University of Technology",
    JU: "Jagannath University",
    JU2: "Jahangirnagar University",
    JUST: "Jashore University of Science and Technology",
    NKU: "Jatiya Kabi Kazi Nazrul Islam University",
    KAU: "Khulna Agricultural University",
    KHAU: "Khulna Khan Bahadur Ahsanullah University",
    KU: "Khulna University",
    KUET: "Khulna University of Engineering and Technology",
    KYAU: "Khwaja Yunus Ali University",
    KAU2: "Kurigram Agricultural University",
    LU: "Leading University",
    MIU: "Manarat International University",
    MBSTU: "Mawlana Bhashani Science and Technology University",
    MU: "Metropolitan University",
    MU2: "Mujibnagar University",
    NPI: "N.P.I. University of Bangladesh",
    NU: "National University, Bangladesh",
    NSTU: "Noakhali Science and Technology University",
    NBIU: "North Bengal International University",
    NEU: "North East University Bangladesh",
    NSU: "North South University",
    NWU: "North Western University",
    NUB: "Northern University of Bangladesh",
    NUBT: "Northern University of Business and Technology, Khulna",
    NDUB: "Notre Dame University Bangladesh",
    PSTU: "Pabna Science and Technology University",
    PaSTU: "Patuakhali Science and Technology University",
    PCIU: "Port City International University",
    PrU: "Premier University",
    PUB: "Presidency University, Bangladesh",
    PU: "Prime University",
    PAU: "Primeasia University",
    PUST: "Pundra University of Science and Technology",
    QU: "Queens University",
    RTMU: "R.T.M. Al-Kabir Technical University",
    RMU: "Rabindra Maitree University",
    RUB: "Rabindra University, Bangladesh",
    RSTU: "Rajshahi Science and Technology University",
    RU: "Rajshahi University",
    RUET: "Rajshahi University of Engineering and Technology",
    RPSU: "Ranada Prasad Shaha University",
    RaSTU: "Rangamati Science and Technology University",
    RUD: "Royal University of Dhaka",
    SUST: "Shahjalal University of Science and Technology",
    SMUCT: "Shanto Mariam University of Creative Technology",
    SFU: "Sheikh Fazilatunnesa Mujib University",
    HSMU: "Sheikh Hasina Medical University",
    SHU: "Sheikh Hasina University",
    SHUST: "Sheikh Hasina University of Science and Technology",
    SBAU: "Sher-e-Bangla Agricultural University",
    SU: "Sonargaon University",
    SOUT: "Southeast University, Bangladesh",
    SUB: "Southern University Bangladesh",
    SBU: "Stamford University Bangladesh",
    SUB2: "State University of Bangladesh",
    SUN: "Sunamganj Science and Technology University",
    SAU: "Sylhet Agricultural University",
    SIU: "Sylhet International University",
    TUCA: "Tagore University of Creative Arts",
    TU: "Teesta University",
    IUOS: "The International University of Scholars",
    MU4: "The Millenium University",
    PU5: "The People's University of Bangladesh",
    TU2: "Times University of Bangladesh",
    TUB: "Trust University, Barishal",
    UIU: "United International University",
    UAP: "University of Asia Pacific",
    UB: "University of Barisal",
    UC: "University of Chittagong",
    UCTC: "University of Creative Technology Chittagong",
    UDA: "University of Development Alternative",
    UD: "University of Dhaka",
    UGV: "University of Global Village",
    UITS: "University of Information Technology and Sciences",
    ULAB: "University of Liberal Arts Bangladesh",
    USTC: "University of Science and Technology Chittagong",
    USEN: "University of Skill Enrichment and Technology",
    USA: "University of South Asia, Bangladesh",
    UU: "Uttara University",
    UV: "Varendra University",
    VUB: "Victoria University of Bangladesh",
    WUB: "World University of Bangladesh",
    ZHST: "Z.H. Sikder University of Science and Technology",
    ZUMS: "ZNRF University of Management Sciences",
};
